### ISSUE TITLE
Azure Cosmos for Postgresql

### ISSUE THREAD

**Issue by csulit** [deno-library/pg#3]
[uncaught application error]: Error - no pg_hba.conf entry for host "136.158.3.13", user "citus", database "citus", no encryption

request: {
  url: "http://localhost:8000/api/v1/listings/search",
  method: "GET",
  hasBody: false
}
response: { status: 404, type: undefined, hasBody: false, writable: true }

    at Connection.readMessage (https://deno.land/x/pg@v0.6.1/connection.ts:77:15)
    at eventLoopTick (ext:core/01_core.js:166:11)
    at async Connection.startup (https://deno.land/x/pg@v0.6.1/connection.ts:62:5)
    at async Connection.connect (https://deno.land/x/pg@v0.6.1/connection.ts:45:7)
    at async Client.connect (https://deno.land/x/pg@v0.6.1/client.ts:31:5)
    at async Pool.connect (https://deno.land/x/pg@v0.6.1/pool.ts:80:5)
    at async executeQuery (file:///Users/christianangelosulit/Documents/GitHub/savills/denorestapi/db/pg.ts:15:18)
    at async file:///Users/christianangelosulit/Documents/GitHub/savills/denorestapi/src/controllers/propertyListing.controller.ts:9:20
    at async dispatch (https://deno.land/x/oak@v12.4.0/middleware.ts:80:7)
    at async dispatch (https://deno.land/x/oak@v12.4.0/middleware.ts:80:7)

**Comment by fuxingZhang** [comment]
Sorry, I haven't been working on TS and JS related development work for over three years and I don't have the ability to maintain it. You should move to other actively maintained repositories.
